[ 2025-01-01 21:06:48,308 ] 12 root - INFO - Starting data ingestion...
[ 2025-01-01 21:06:51,862 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-01 21:06:51,865 ] 16 root - INFO - Starting data preprocessing...
[ 2025-01-01 21:06:51,950 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-01 21:06:51,950 ] 20 root - INFO - Starting model training...
[ 2025-01-01 21:06:51,966 ] 25 root - INFO - Data loaded successfully.
[ 2025-01-01 21:06:51,970 ] 29 root - INFO - Missing values handled.
[ 2025-01-01 21:06:51,972 ] 36 root - INFO - Categorical variables encoded.
[ 2025-01-01 21:06:57,459 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD1BA58AF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-01-01 21:07:05,834 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD1BA5B250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-01-01 21:07:18,795 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD1BA5A020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-01-01 21:07:39,747 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD1BA59F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-01-01 21:08:16,571 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD1BA59E70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2025-01-01 21:08:20,642 ] 71 root - ERROR - An error occurred during model training: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FD1BA58F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
