[ 2024-12-31 22:27:56,441 ] 12 root - INFO - Starting data ingestion...
[ 2024-12-31 22:27:59,616 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2024-12-31 22:27:59,618 ] 16 root - INFO - Starting data preprocessing...
[ 2024-12-31 22:27:59,747 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2024-12-31 22:27:59,747 ] 20 root - INFO - Starting model training...
[ 2024-12-31 22:27:59,786 ] 25 root - INFO - Data loaded successfully.
[ 2024-12-31 22:27:59,790 ] 29 root - INFO - Missing values handled.
[ 2024-12-31 22:27:59,793 ] 36 root - INFO - Categorical variables encoded.
[ 2024-12-31 22:28:05,110 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8A441AB60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-31 22:28:13,573 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8A4419840>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-31 22:28:25,702 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8A4418FA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-31 22:28:46,761 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8A4419900>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-31 22:29:23,541 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8A44196C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[ 2024-12-31 22:29:27,644 ] 71 root - ERROR - An error occurred during model training: API request to http://localhost:5000/api/2.0/mlflow/runs/create failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E8A4419CF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
