[ 2025-01-02 16:14:07,335 ] 49 root - INFO - Setting up MLflow...
[ 2025-01-02 16:14:07,350 ] 58 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-02 16:14:07,350 ] 89 root - INFO - Starting data ingestion...
[ 2025-01-02 16:14:10,685 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-02 16:14:10,686 ] 93 root - INFO - Starting data preprocessing...
[ 2025-01-02 16:14:10,723 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-02 16:14:10,723 ] 97 root - INFO - Starting model training...
[ 2025-01-02 16:14:10,724 ] 74 root - INFO - Starting a new MLflow run...
[ 2025-01-02 16:14:11,470 ] 99 root - INFO - Active MLflow run ID: eaa939f267ed49ee96ef868d98f1b7f5
[ 2025-01-02 16:14:11,479 ] 25 root - INFO - Data loaded successfully.
[ 2025-01-02 16:14:11,479 ] 29 root - INFO - Missing values handled.
[ 2025-01-02 16:14:11,481 ] 36 root - INFO - Categorical variables encoded.
[ 2025-01-02 16:14:11,483 ] 71 root - ERROR - An error occurred during model training: Run with UUID eaa939f267ed49ee96ef868d98f1b7f5 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
[ 2025-01-02 16:14:15,612 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002286A3BB3A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=eaa939f267ed49ee96ef868d98f1b7f5&run_id=eaa939f267ed49ee96ef868d98f1b7f5
[ 2025-01-02 16:14:24,572 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002286A3BB220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=eaa939f267ed49ee96ef868d98f1b7f5&run_id=eaa939f267ed49ee96ef868d98f1b7f5
[ 2025-01-02 16:14:37,109 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002286A3BB130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=eaa939f267ed49ee96ef868d98f1b7f5&run_id=eaa939f267ed49ee96ef868d98f1b7f5
[ 2025-01-02 16:14:57,367 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002286A3BA500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=eaa939f267ed49ee96ef868d98f1b7f5&run_id=eaa939f267ed49ee96ef868d98f1b7f5
[ 2025-01-02 16:15:34,299 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002286A3BACB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=eaa939f267ed49ee96ef868d98f1b7f5&run_id=eaa939f267ed49ee96ef868d98f1b7f5
[ 2025-01-02 16:15:38,414 ] 108 root - ERROR - An unexpected error occurred: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=eaa939f267ed49ee96ef868d98f1b7f5&run_id=eaa939f267ed49ee96ef868d98f1b7f5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002286A3BA590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
