[ 2025-01-02 16:18:55,997 ] 49 root - INFO - Setting up MLflow...
[ 2025-01-02 16:18:56,015 ] 58 root - INFO - MLflow setup completed with experiment: Medical Insurance Predictor
[ 2025-01-02 16:18:56,016 ] 89 root - INFO - Starting data ingestion...
[ 2025-01-02 16:18:59,295 ] 20 root - INFO - Data downloaded successfully to D:/My projects/Medical Insurane Predictor/data/raw_data\insurance.csv
[ 2025-01-02 16:18:59,296 ] 93 root - INFO - Starting data preprocessing...
[ 2025-01-02 16:18:59,387 ] 35 root - INFO - Data preprocessed and saved to D:/My projects/Medical Insurane Predictor/data/Processed_data\processed_data.csv
[ 2025-01-02 16:18:59,388 ] 97 root - INFO - Starting model training...
[ 2025-01-02 16:18:59,388 ] 74 root - INFO - Starting a new MLflow run...
[ 2025-01-02 16:19:01,453 ] 99 root - INFO - Active MLflow run ID: d8a426d9ffba4426a6feb6d707d8264f
[ 2025-01-02 16:19:05,617 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569376FE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 16:19:14,562 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569377520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 16:19:27,562 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569377220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 16:19:48,398 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569377310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 16:20:25,031 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569376D40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor
[ 2025-01-02 16:20:29,115 ] 156 root - ERROR - An error occurred during model training: API request to http://localhost:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=insurance_predictor (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569376E60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[ 2025-01-02 16:20:33,198 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569374910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=d8a426d9ffba4426a6feb6d707d8264f&run_id=d8a426d9ffba4426a6feb6d707d8264f
[ 2025-01-02 16:20:42,153 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A5693745B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=d8a426d9ffba4426a6feb6d707d8264f&run_id=d8a426d9ffba4426a6feb6d707d8264f
[ 2025-01-02 16:20:54,617 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569374BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=d8a426d9ffba4426a6feb6d707d8264f&run_id=d8a426d9ffba4426a6feb6d707d8264f
[ 2025-01-02 16:21:15,716 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569376B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=d8a426d9ffba4426a6feb6d707d8264f&run_id=d8a426d9ffba4426a6feb6d707d8264f
[ 2025-01-02 16:21:52,397 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A569376290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/get?run_uuid=d8a426d9ffba4426a6feb6d707d8264f&run_id=d8a426d9ffba4426a6feb6d707d8264f
[ 2025-01-02 16:21:56,504 ] 108 root - ERROR - An unexpected error occurred: API request to http://localhost:5000/api/2.0/mlflow/runs/get failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/runs/get?run_uuid=d8a426d9ffba4426a6feb6d707d8264f&run_id=d8a426d9ffba4426a6feb6d707d8264f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A5693765F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
